name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies and build
        run: |
          go mod tidy
          go build -o application main.go
          chmod +x application
          ls -la

      - name: Prepare deployment package
        run: |
          echo "web: ./application" > Procfile
          zip -r application.zip application Procfile go.mod go.sum
          ls -la

      - name: Verify deployment package
        run: |
          echo "Contents of application.zip:"
          unzip -l application.zip

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: vibin
          environment_name: Vibin-env
          region: ap-south-1
          version_label: "build-${{ github.sha }}-${{ github.run_number }}"
          deployment_package: application.zip
          wait_for_deployment: true

      - name: Confirm Deployment
        run: |
          echo "Deployment triggered for version: build-${{ github.sha }}-${{ github.run_number }}"