name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # Adjust to the Go version you're using

      # Step 3: Install dependencies and build the application
      - name: Install dependencies and build
        run: |
          go mod tidy
          go build -o application main.go

      # Step 4: Prepare application for deployment
      - name: Prepare deployment package
        run: |
          mkdir -p deployment
          mv application deployment/
          zip -r application.zip deployment/

      # Step 5: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: vibin-server # Replace with your Beanstalk app name
          environment_name: Vibin-server-env # Replace with your Beanstalk environment name
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: application.zip